(function(){
  let modal,frame,view,currentPdfUrl,currentPdfBytes,currentPdfName='MSME Profiling Form.pdf';
  const S=v=>String(v??'').trim(), lower=v=>S(v).toLowerCase();
  const has=(value,needle)=>lower(value).includes(lower(needle));
  function loadScript(src){return new Promise((resolve,reject)=>{if(window.PDFLib)return resolve();const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(new Error('The PDF editor could not be loaded.'));document.head.appendChild(s);});}
  async function bytes(url){const r=await fetch(url,{credentials:'same-origin',cache:'no-store'});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||'The official PDF could not be loaded.');return new Uint8Array(await r.arrayBuffer());}
  function trimTo(font,text,width,size,min=5){text=S(text);while(size>min&&font.widthOfTextAtSize(text,size)>width)size-=.25;if(font.widthOfTextAtSize(text,size)>width){const tail='...';while(text&&font.widthOfTextAtSize(text+tail,size)>width)text=text.slice(0,-1);text+=tail;}return [text,size];}
  function text(page,font,value,x,baseline,width,size=8){value=S(value);if(!value)return;size*=1.18*(page.__msmeTextScale||1);[value,size]=trimTo(font,value,width,size,page.__msmeTextMin||6.8);page.drawText(value,{x,y:792-baseline-6+(page.__msmeTextLift||0),font,size,color:PDFLib.rgb(.025,.025,.025)});}
  function center(page,font,value,left,right,baseline,size=8){value=S(value);if(!value)return;size*=1.18*(page.__msmeTextScale||1);[value,size]=trimTo(font,value,right-left-3,size,page.__msmeTextMin||6.8);const w=font.widthOfTextAtSize(value,size);page.drawText(value,{x:left+(right-left-w)/2,y:792-baseline-6+(page.__msmeTextLift||0),font,size,color:PDFLib.rgb(.025,.025,.025)});}
  function lines(page,font,value,x,top,width,lineHeight=10,size=7.5,maxLines=3){const words=S(value).split(/\s+/).filter(Boolean);if(!words.length)return;const rows=[];let row='';for(const word of words){const test=row?row+' '+word:word;if(font.widthOfTextAtSize(test,size)<=width)row=test;else{if(row)rows.push(row);row=word;}}if(row)rows.push(row);rows.slice(0,maxLines).forEach((line,i)=>text(page,font,line+(i===maxLines-1&&rows.length>maxLines?'...':''),x,top+i*lineHeight,width,size));}
  function mark(page,on,x,top){if(!on)return;top-=page.__msmeMarkLift||0;const inset=page.__msmeMarkInset||1.7,end=page.__msmeMarkEnd||8.1,weight=page.__msmeMarkWeight||.72,c=PDFLib.rgb(.02,.02,.02),y=792-top;page.drawLine({start:{x:x+inset,y:y-inset},end:{x:x+end,y:y-end},thickness:weight,color:c});page.drawLine({start:{x:x+end,y:y-inset},end:{x:x+inset,y:y-end},thickness:weight,color:c});}
  function financialMark(page,on,x,top){if(!on)return;const c=PDFLib.rgb(.02,.02,.02),y=792-(top-8),inset=2.35,end=7.25;page.drawLine({start:{x:x+inset,y:y-inset},end:{x:x+end,y:y-end},thickness:.68,color:c});page.drawLine({start:{x:x+end,y:y-inset},end:{x:x+inset,y:y-end},thickness:.68,color:c});}
  function pageThreeMark(page,on,x,top){if(!on)return;const c=PDFLib.rgb(.02,.02,.02),y=792-(top-8),inset=2.35,end=7.25;page.drawLine({start:{x:x+inset,y:y-inset},end:{x:x+end,y:y-end},thickness:.68,color:c});page.drawLine({start:{x:x+end,y:y-inset},end:{x:x+inset,y:y-end},thickness:.68,color:c});}
  function list(value){return S(value).split(/\s*(?:,|;|\|)\s*/).filter(Boolean);}
  function other(value,known){return list(value).filter(v=>!known.some(k=>has(v,k))).join(', ');}
  function money(value){value=S(value);return value&&/^\d+(?:\.\d+)?$/.test(value)?Number(value).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2}):value;}
  function date(value){const m=S(value).match(/^(\d{4})-(\d{2})-(\d{2})/);return m?m[2]+'/'+m[3]+'/'+m[1]:S(value);}
  function dateParts(value){const m=S(value).match(/^(\d{4})-(\d{2})-(\d{2})/);return m?{month:m[2],day:m[3],year:m[1]}:{month:'',day:'',year:''};}
  function longDate(value){const m=S(value).match(/^(\d{4})-(\d{2})-(\d{2})/);if(!m)return S(value);return new Date(Number(m[1]),Number(m[2])-1,Number(m[3])).toLocaleDateString('en-PH',{month:'long',day:'numeric',year:'numeric'});}
  async function build(id){
    await loadScript('vendor/pdf-lib/pdf-lib.min.js?v=1.17.1');
    const base='msme_form.php?id='+encodeURIComponent(id),[data,template]=await Promise.all([fetch(base+'&action=data',{credentials:'same-origin',cache:'no-store'}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||'MSME data could not be loaded.');return j;}),bytes(base+'&action=template')]);
    const doc=await PDFLib.PDFDocument.load(template),font=await doc.embedFont(PDFLib.StandardFonts.TimesRoman),bold=await doc.embedFont(PDFLib.StandardFonts.TimesRomanBold),p=doc.getPages(),r=data.record||{};p[0].__msmeTextScale=1.25;p[0].__msmeTextMin=8.2;p[0].__msmeTextLift=1;p[1].__msmeMarkLift=8;p[1].__msmeMarkInset=2;p[1].__msmeMarkEnd=7.8;p[1].__msmeMarkWeight=.68;p[2].__msmeMarkLift=10;
    const own=S(r.ownership_type),nature=S(r.business_nature),edu=S(r.educational_attainment);
    center(p[0],font,r.business_name,166,551,169,8.5);
    [['sole',161,184],['partnership',332,184],['corporation',469,184],['cooperative',16,203]].forEach(a=>mark(p[0],has(own,a[0]),a[1],a[2]));
    [['food',145,223],['retail',276,223],['services',394,223],['handicraft',468,223],['agri',16,242]].forEach(a=>mark(p[0],has(nature,a[0]),a[1],a[2]));
    const natureOther=other(nature,['food','retail','trading','services','handicraft','agri']);mark(p[0],Boolean(natureOther),145,242);text(p[0],font,natureOther,213,243,105,7.2);
    const products=list(r.primary_products),prices=list(r.product_price);for(let i=0;i<10;i++){const right=i>=5,nameLeft=right?319:29,nameRight=right?509:219,priceLeft=right?531:249,priceRight=right?567:285,top=282+(i%5)*19.4;center(p[0],font,products[i],nameLeft,nameRight,top,7.2);center(p[0],font,money(prices[i]),priceLeft,priceRight,top,7.2);}
    text(p[0],font,r.year_started,180,379,30,8);center(p[0],font,r.business_permit_no,347,567,379,8);center(p[0],font,date(r.permit_validity),93,231,397,8);center(p[0],font,r.dti_no,159,569,417,8);center(p[0],font,r.tin_no,201,566,436,8);
    center(p[0],font,r.contact_no,166,566,475,8);center(p[0],font,r.email||r.business_email,111,566,492,8);center(p[0],font,r.business_social_media,207,566,510,8);
    center(p[0],font,data.full_name,92,477,573,8);center(p[0],font,r.sex,516,563,573,8);center(p[0],font,r.contact_no,150,330,590,8);const dob=dateParts(r.birthdate);center(p[0],font,dob.month,432,450,593,7.3);center(p[0],font,dob.day,455,473,593,7.3);center(p[0],font,dob.year,477,504,593,7.3);center(p[0],font,data.age,535,566,590,8);
    [['single',130,607],['married',232,607],['widow',364,607]].forEach(a=>mark(p[0],has(r.civil_status,a[0]),a[1],a[2]));center(p[0],font,data.address,18,583,647,8);
    [['elementary',18,681],['high school',140,681],['college undergraduate',242,681],['college graduate',435,681],['vocational',18,700]].forEach(a=>mark(p[0],has(edu,a[0]),a[1],a[2]));const eduOther=other(edu,['elementary','high school','college undergraduate','college graduate','vocational','technical']);mark(p[0],Boolean(eduOther),242,700);text(p[0],font,eduOther,311,700,127,7.2);const work=S(r.work_experience);if(/^(?:n\/?a|none|not applicable)$/i.test(work))center(p[0],font,'N/A',18,583,748,7.5);else lines(p[0],font,work,30,748,540,11,7.5,3);
    const assets=S(r.assets_owned),utilities=S(r.utility_needs);
    [['cart',195,47],['cooking',316,47],['refrigerator',492,47]].forEach(a=>mark(p[1],has(assets,a[0]),a[1],a[2]));mark(p[1],has(assets,'vehicle'),18.6,68.3);let residual=other(assets,['cart','stall','cooking','refrigerator','vehicle']);mark(p[1],Boolean(residual),108,69);text(p[1],font,residual,171,69,420,7.5);
    [['electricity',127,89],['water',254,89],['storage',364,89],['internet',480,89]].forEach(a=>mark(p[1],has(utilities,a[0]),a[1],a[2]));residual=other(utilities,['electricity','water','storage','internet','data']);mark(p[1],Boolean(residual),18,117);text(p[1],font,residual,85,118,505,7.5);
    center(p[1],font,r.hr_male,226,293,182,8);center(p[1],font,r.hr_female,364,436,182,8);center(p[1],font,r.hr_total,485,565,182,8);center(p[1],font,r.emp_regular,143,181,219,8);center(p[1],font,r.emp_seasonal,143,181,237,8);center(p[1],font,r.emp_contractual,143,181,252,8);center(p[1],font,r.emp_family,143,181,270,8);const skills=S(r.hr_skills);if(!skills||/^(?:0|n\/?a|none|not applicable)$/i.test(skills))center(p[1],font,'N/A',18,590,309,8);else lines(p[1],font,skills,30,309,540,18,8,4);
    const capital=S(r.source_of_capital);[['own savings',154,424],['loan bank',297,423],['loan (bank',297,423],['coop',443,423],['borrowed',18,447],['government',297,447]].forEach(a=>financialMark(p[1],has(capital,a[0]),a[1],a[2]));residual=other(capital,['own savings','loan bank','bank loan','loan coop','coop','mfi','borrowed','family','friends','government']);financialMark(p[1],Boolean(residual),18,471);text(p[1],font,residual,82,473,490,9);
    [['micro',17.3,507],['small',127,505],['medium',351.3,507]].forEach(a=>financialMark(p[1],has(r.business_size,a[0]),a[1],a[2]));center(p[1],font,money(r.initial_capital),194,285,538,10);center(p[1],font,money(r.current_capital),499,571,538,10);center(p[1],font,money(r.daily_earnings),401,570,568,10);
    const payment=S(r.mode_of_payment),distribution=S(r.distribution_channels);[['cash',18,640],['e-wallet',126,640],['gcash',126,640],['bank transfer',356,640]].forEach(a=>financialMark(p[1],has(payment,a[0]),a[1],a[2]));residual=other(payment,['cash','e-wallet','gcash','paymaya','bank transfer']);financialMark(p[1],Boolean(residual),18,659);text(p[1],font,residual,82,660,490,9);
    [['direct',18,697],['retailer',155,697],['wholesaler',252,697],['online',367,697]].forEach(a=>financialMark(p[1],has(distribution,a[0]),a[1],a[2]));residual=other(distribution,['direct selling','retailer','wholesaler','online platform']);financialMark(p[1],Boolean(residual),18,720);text(p[1],font,residual,82,721,490,9);
    const assisted=S(r.assistance_availed),past=S(r.past_programs),needed=S(r.programs_needed),challenges=S(r.challenges_encountered);
    pageThreeMark(p[2],has(r.availed_before,'yes'),397,52);pageThreeMark(p[2],has(r.availed_before,'no'),464,53);
    [['dti',163,97],['dole',390,97],['tesda',24,121],['da/',191,121],['dswd',191,121],['lgu',386,121]].forEach(a=>pageThreeMark(p[2],has(assisted,a[0]),a[1],a[2]));residual=other(assisted,['dti','dole','tesda','da/','dswd','lgu']);pageThreeMark(p[2],Boolean(residual),24,137);text(p[2],font,residual,91,140,490,7.4);
    [['skills training',24,178],['trade fair',161,178],['packaging',337,178],['business advisory',24,198],['shared service',247,198]].forEach(a=>pageThreeMark(p[2],has(past,a[0]),a[1],a[2]));residual=other(past,['skills training','trade fair','exhibit','product packaging','labeling','business advisory','shared service']);pageThreeMark(p[2],Boolean(residual),24,216);text(p[2],font,residual,91,218,490,7.4);
    [['financing',24,261],['skills training',24,275],['marketing',24,293],['product development',24,311],['business registration',24,331],['export',24,347]].forEach(a=>pageThreeMark(p[2],has(needed,a[0]),a[1],a[2]));residual=other(needed,['financing','skills training','marketing','product development','innovation','business registration','export']);pageThreeMark(p[2],Boolean(residual),24,365);text(p[2],font,residual,91,364,490,7.4);
    [['capital',24,444],['marketing',24,464],['technical skills',24,480],['raw materials',24,499],['technology',24,521],['infrastructure',24,538],['permits',24,557],['competition',24,578]].forEach(a=>pageThreeMark(p[2],has(challenges,a[0]),a[1],a[2]));residual=other(challenges,['capital','credit','marketing','promotion','technical skills','training','raw materials','technology','equipment','infrastructure','permits','documentation','competition']);pageThreeMark(p[2],Boolean(residual),24,595);text(p[2],font,residual,91,597,490,7.4);
    center(p[2],bold,data.full_name,86,334,718,9);center(p[2],font,longDate(r.created_at),44,207,734,8.5);
    currentPdfName=(S(data.full_name)||'Applicant').replace(/[<>:"/\\|?*\x00-\x1F]/g,'').replace(/\s+/g,' ').trim()+' MSME Profiling Form.pdf';doc.setTitle('MSME Profiling Form - '+data.full_name);doc.setSubject('Official MSME Profiling Form');return await doc.save();
  }
  function ensure(){if(modal)return;const css=document.createElement('link');css.rel='stylesheet';css.href='spes_form_modal.css?v=20260813d';document.head.appendChild(css);modal=document.createElement('div');modal.className='spes-form-modal';modal.setAttribute('aria-hidden','true');modal.innerHTML='<div class="spes-form-dialog" role="dialog" aria-modal="true" aria-label="MSME profiling form"><aside class="spes-form-tools"><div class="spes-form-heading"><span class="spes-form-icon">DOC</span><div><h2>MSME Form</h2><p>Official profiling document</p></div></div><div class="spes-form-badge"><span></span> Profiling Form <b>3 pages</b></div><div class="spes-action-label">Document actions</div><button class="spes-tool-btn primary" data-action="print"><span class="spes-btn-icon">&#128424;</span><span>Print document<small>Open the print dialog</small></span></button><button class="spes-tool-btn" data-action="pdf"><span class="spes-btn-icon">&#8681;</span><span>Download PDF<small>Save the completed official form</small></span></button><div class="spes-form-note">MSME details are ready for review, printing, or download.</div><button class="spes-tool-btn secondary" data-action="close"><span class="spes-btn-icon">&#10005;</span><span>Close preview</span></button></aside><main class="spes-form-view"><div class="spes-form-loading"><span class="spes-loader"></span><strong>Preparing official form</strong><small>Positioning MSME information...</small></div><iframe class="spes-form-frame" title="Official filled MSME PDF"></iframe></main></div>';document.body.appendChild(modal);frame=modal.querySelector('iframe');view=modal.querySelector('.spes-form-view');frame.addEventListener('load',()=>view.classList.add('loaded'));modal.addEventListener('click',e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(!a){if(e.target===modal)close();return;}if(a==='close')close();if(a==='print'){frame.contentWindow.focus();frame.contentWindow.print();}if(a==='pdf'&&currentPdfBytes){const blob=new Blob([currentPdfBytes],{type:'application/pdf'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=currentPdfName;link.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('is-open'))close();});}
  function close(){modal.classList.remove('is-open');modal.setAttribute('aria-hidden','true');document.body.style.overflow='';}
  window.openMsmeForm=async function(id){const profile=document.getElementById('profileModal');if(profile){profile.classList.remove('show');profile.setAttribute('aria-hidden','true');}ensure();currentPdfBytes=null;view.classList.remove('loaded');modal.classList.add('is-open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';try{currentPdfBytes=await build(id);if(currentPdfUrl)URL.revokeObjectURL(currentPdfUrl);currentPdfUrl=URL.createObjectURL(new Blob([currentPdfBytes],{type:'application/pdf'}));frame.src=currentPdfUrl+'#page=1&zoom=page-fit';}catch(err){view.querySelector('.spes-form-loading').textContent=err.message||'The official form could not be prepared.';console.error(err);}};
})();
